### ISSUE TITLE
Question: Timeout for lock

### ISSUE THREAD

**Issue by szikszail** [dignifiedquire/lock-me#2]
Hi,

I was wondering whether there is any timeout or waiting mechanism is built in this package, which would wait for the lock file to be released? I am asking this because it is not clear to me based on the source.

Thank you in advance for the answer!

**Comment by dignifiedquire** [comment]
No there is not currently, you can check if the resource is locked manually, but there is no functionality to wait until it is unlocked currently

**Comment by szikszail** [comment]
Thank you for the quick answer. And are you planning to add such functionality?
